### ISSUE TITLE
[Bug] Repels not working after randomization

### ISSUE THREAD

**Issue by Nezzygirl7** [upr-fvx/universal-pokemon-randomizer-fvx#11]
After randomization of Pokemon Moon Repels no longer work. I use a repel and wild encounters still happen.

Settings:
Trainer pokémon set to random 
-No early Wonder guard 
-Allow alternate forms
-randomized trainer names and trainer class names 
Totem pokémon set to random 
-ally pokémon random 
-auras random 
-randomize held items
-allow alternate forms

System:
 - Operating System: Windows 10 
 - Java Version:  18.0.2.1
 - Randomizer Version: FVX 1.0.0

**Comment by foxoftheasterisk** [comment]
Hmm. I can't reproduce this (in Sun). 

Your leading party member is higher level than the wild Pokémon you're encountering, right? (Repels only block lower level encounters; that's not a bug.)
