### ISSUE TITLE
[Bug] The 'Update Base Stats to Generation' setting doesn't work for some pokemon

### ISSUE THREAD

**Issue by TendrilChicken** [upr-fvx/universal-pokemon-randomizer-fvx#16]
The 'Update Base Stats to Generation' setting doesn't work for some pokemon:

```
Pikachu
        Defense 30 -> 40
        Special Defense 40 -> 50

Raichu
        Speed 100 -> 110
        
Wigglytuff
        Special Attack 75 -> 85
```

I looked at this list https://github.com/upr-fvx/universal-pokemon-randomizer-fvx/wiki/Pokemon-Base-Statistics and compared it to my Gen 3 log. There might be other pokemon whose stats weren't updated, but I can definitely say that between gen 1 to gen 3 that these are the only pokemon bugged.

My log:

```
--Pokemon Base Stats & Types--
NUM|NAME         |TYPE             |  HP| ATK| DEF|SATK|SDEF| SPD|ABILITY1    |ABILITY2    |ITEM
 25|PIKACHU      |ELECTRIC         |  35|  55|  30|  50|  40|  90|STATIC      |-------     |
 26|RAICHU       |ELECTRIC         |  60|  90|  55|  90|  80|  92|STATIC      |-------     |
 40|WIGGLYTUFF   |NORMAL           | 140|  70|  45|  75|  50|  45|CUTE CHARM  |-------     |
```

I'm no programmer, but I was able to find this https://github.com/upr-fvx/universal-pokemon-randomizer-fvx/blob/master/src/com/dabomstew/pkrandom/updaters/PokemonBaseStatUpdater.java#L51

And it looks someone copy-pasted Nidoqueen's 92 attack onto Raichu's speed.

**Comment by voliol** [comment]
Thanks for pointing this out!
It has been fixed for the next version :)
