### ISSUE TITLE
Crash with randomization rpocess

### ISSUE THREAD

**Issue by Cyberk999** [upr-fvx/universal-pokemon-randomizer-fvx#18]
[error_2024-12-01-16-34-20.txt](https://github.com/user-attachments/files/17970401/error_2024-12-01-16-34-20.txt)

Probably has to do with trainers and their held items.

**Comment by foxoftheasterisk** [comment]
An interesting corner case; it was trying to assign a weakness-reducing berry for the Normal type, an item that does not (technically) exist, since in the base game no Pokemon is weak to Normal type.

Anyway, it's now fixed in source.
