### ISSUE TITLE
[Bug] Several Options in Pokemon Platinum Break the Randomizer

### ISSUE THREAD

**Issue by TopOfAllWorlds** [upr-fvx/universal-pokemon-randomizer-fvx#19]
**Describe the bug**
TM/HM Compatibility and Move Tutor option Follow Evolution creates an unhandled exception when trying to save the ROM. The same thing happens when attempting to randomize the colors at all.

**To Reproduce**
1. Go to (TM/HMs & Tutors) or (Graphics)
2. Click on Follow Evolutions for (TM/HMs & Tutors) or select random for (Graphics)
3. Hit the "Randomize (Save)" button

**Expected behavior**
It's supposed to do the function listed when selecting the options

**Screenshots**
<img width="384" alt="d353c9a337166bc37e2bd2d1c5bb9013" src="https://github.com/user-attachments/assets/bc2a3e44-a15b-4150-9656-1e9102d40e05" />

**System (please complete the following information):**
 - Windows 10
 - Java Version: 1.8.0_431
 - Randomizer Version: 1.1.0

**Additional context**
Logs 
[error_2024-12-11-09-50-18.txt](https://github.com/user-attachments/files/18097981/error_2024-12-11-09-50-18.txt)
[error_2024-12-11-09-51-45.txt](https://github.com/user-attachments/files/18097983/error_2024-12-11-09-51-45.txt)
Reproduction of Original Error Encounter: [error_2024-12-11-09-54-41.txt](https://github.com/user-attachments/files/18097984/error_2024-12-11-09-54-41.txt)

**Comment by foxoftheasterisk** [comment]
Right, this is related to CUEH and forms, so I'll let Voliol handle it.

**Comment by voliol** [comment]
Fixed for the next release. Thank you for your report :)
