### ISSUE TITLE
Conversion = 'L' error when randomizing

### ISSUE THREAD

**Issue by Cyberk999** [upr-fvx/universal-pokemon-randomizer-fvx#2]
[error_2024-07-12-17-07-26.txt](https://github.com/user-attachments/files/16199297/error_2024-07-12-17-07-26.txt)
Apparently: "The format string used in the maybeLogTrainerChanges method contains an invalid conversion character 'L'."
but otherwise it will not let me randomize this game using certain settings.

**Comment by Cyberk999** [comment]
[error_2024-07-12-17-15-15.txt](https://github.com/user-attachments/files/16199317/error_2024-07-12-17-15-15.txt)
This error now too when i rty and do the same thing with ORAS

**Comment by voliol** [comment]
Thanks for pointing out the bugs, taking a look at both of them now.

**Comment by voliol** [comment]
The latter bug should be fixed for the next version.

**Comment by voliol** [comment]
The second bug has been handled as well. Closing issue.
