### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Wooftydog** [upr-fvx/universal-pokemon-randomizer-fvx#3]
[error_2024-07-13-07-53-34.txt](https://github.com/user-attachments/files/16202226/error_2024-07-13-07-53-34.txt)

Issue with randomizing trainer sensible items with Omega Ruby. Removing it let the randomizer succeed.

Also some ideas: 
Clothing Randomizer for X/Y, S/M, and US/UM
Type Chart Randomizer for Gen 6 & 7

**Comment by voliol** [comment]
Bug identified and fixed for the next version. Thanks for pointing it out! :)
