### ISSUE TITLE
[Bug] Random Basic with 2 stages and Any type triangle 

### ISSUE THREAD

**Issue by aodnightshade** [upr-fvx/universal-pokemon-randomizer-fvx#7]
**Describe the bug**
Using Random (basic Pokemon with 2 evolutions) and Any type triangle causes the the Starters to no longer require 2 stages. I.E. Wingull, Ponyta, Nincada, Scrafty all appeared.

**Screenshots**
https://puu.sh/KccJS/8c8ac41511.png Example.
https://puu.sh/KccKT/2cb04c294a.png

**Comment by aodnightshade** [comment]
Actually after extra testing, it seems to happen with any of the Type Restrictions with "basic Pokemon with 2 Evolutions".

**Comment by foxoftheasterisk** [comment]
After some testing... this has nothing to do with Type restrictions, that setting just doesn't work at all. (Well, it seems to guarantee _one_ evolution...)

**Comment by foxoftheasterisk** [comment]
Ok, fixed in source.
