### ISSUE TITLE
[Bug] Keep Type Themed Trainers' Themes - Platinum Gyms Randomized Based on Diamond/Pearl Order

### ISSUE THREAD

**Issue by macobra52** [upr-fvx/universal-pokemon-randomizer-fvx#9]
**Describe the bug**
When randomizing Pokemon Platinum with the 'Keep Type Themed Trainers' Themes' option, the types of the 3rd, 4th, and 5th Gyms are incorrectly randomized based on their Diamond/Pearl order instead of their Platinum order.

Fantina's Gym received fighting type Pokemon (instead of ghost)
Maylene's Gym received water type Pokemon (instead of fighting)
Crasher Wake's Gym received ghost type Pokemon (instead of water)

**Expected behavior**
Fantina's Gym should receive ghost type Pokemon, since it is the 3rd gym in Platinum
Maylene's Gym should receive fighting type Pokemon, since it is the 4th gym in Platinum
Crasher Wake's Gym should receive water type Pokemon, since it is the 5th gym in Platinum

Randomizer Version: 0.1.1
[platinum random.nds.log](https://github.com/user-attachments/files/16529101/platinum.random.nds.log)

**Comment by foxoftheasterisk** [comment]
Ah! Thank you. Fixed in source.
